### ISSUE TITLE
Cannot change Queued Song

### ISSUE THREAD

**Issue by JefferysTuber** [swimmadude66/YTRadio#20]
When songs are added to the queue, the song is locked-in and the playlist view moves that track to the bottom.
This makes it impossible to change your next track, it also makes it a bit confusing if you want to delete your last played track.

This is likely somewhat of an expected behavior rather than a bug.... but it would be helpful if the next track (the one queued up) was indicated somehow other than just being moved to the bottom.

It is possible this causing some of the confusion we've had on playlists looping or advancing oddly. Took me a while to figure this one out, had tried to explain it before.

Edit: Additionally the playlist displayed below as the next track, is actually the second to next. It shows whats at the top of the playlist, but the song listed in the queue is the actual next track.

**Comment by JefferysTuber** [comment]
Additionally-

Once the song has advanced in the playlist due to moving to the queue, it remains in its numerical position. Dispite adding new songs to playlist. Again, now that I think I know whats going on, this is less of a bug than an issue with the way you've set the queuing up.

Playlist set-
    Playlist: A, B, C

Queue joined-
    Playing: A
    Queued: B
    'Next': C
    Playlist: C, A, B

New songs-
    Playing: A
    Queued: B
    'Next': C
    Playlist: C, A, B, D, E, F, G

E moved to top-
    Playing: A
    Queued: B
    'Next': E
    Playlist: E, C, A, B, D, F, G

User will experience their 'Next' seemingly ignored, and A will play again before new tracks F and G

**Comment by localyost3000** [comment]
I am going to tag this as "wontfix" not because your complaint is invalid, but because I am rethinking the queue entirely. the original idea was that queuing users instead of videos complicated things, but I am rethinking that position. It may be better to allow users to change their next song by simply grabbing the next-up user's song. 

Another option  is a hybridized version which locks in the next-user's song, while allowing the rest of the queue to change until their are on deck. Either way, this would be a pretty big re-design and will most likely be deferred for now.

**Comment by localyost3000** [comment]
This will be fixed soon, in order to allow for control over who can and cannot join/stay in the queue.

**Comment by localyost3000** [comment]
Fixed in Beta 0.4.0
