### ISSUE TITLE
Unauthenticated user can skip tracks

### ISSUE THREAD

**Issue by DavidErvin** [swimmadude66/YTRadio#58]
If I'm not logged in, I can skip tracks.

**Comment by DavidErvin** [comment]
Correction - if I WAS logged in, but the app restarts (for example, maybe other cases where I get disconnected or lose my cookie somehow), I can skip songs but not do anything else.  The Skip button is active and seems to work OK in this case.  If I reload the page and I'm not logged in, it disables as expected.

**Comment by localyost3000** [comment]
ok, I understand what's happening her. and I'm torn on whether or not to fix it. It will only be available if you were logged in as an admin this session. that means its not exposing to other users, only those who were once signed in as admins since the last kick.

I'm kind of ok with this, since that means admins can skip even if the sockets lose their mind

**Comment by localyost3000** [comment]
I would rather fix the issue of socket disconnects, so I'm going to abandon this one for now.
